version: '3.4'

services:
    nginx:
      build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
      depends_on:
        - php
      volumes:
        - ./app:/var/www/html:ro
        - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      ports:
        - 80:80
        - 443:443

    php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
      depends_on:
        - mysql
      volumes:
        - ./app:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

    mysql:
      image: mysql:5.7
      volumes:
        - ./data/mysql:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: 'secret'
